tasks:
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      unzip awscliv2.zip 
      sudo ./aws/install 
      cd $THEIA_WORKSPACE_ROOT

  - name: amplify-cli
    env:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    init: |
      curl -o- -L https://github.com/aws-amplify/amplify-cli/releases/latest/download/amplify-ubuntu.zip | tar -xz -C /tmp
      sudo mv /tmp/amplify /usr/local/bin/
      chmod +x /usr/local/bin/amplify
      amplify configure

  - name: react-js
    command: |
      echo $PATH
      cd frontend-react-js
      npm i 

  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ 'lsb_release -cs' -pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ckolkman.vscode-postgres
